### ISSUE TITLE
Invalid argument: Map<dynamic, dynamic> on message_codecs.dart

### ISSUE THREAD

**Issue by nicolaslara** [torusresearch/torus-direct-flutter-sdk#4]
Getting the following error when trying to run the example:

```
E/flutter (24827): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument: Map<dynamic, dynamic>
E/flutter (24827): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:419:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:416:9)
E/flutter (24827): torusresearch/torus-direct-web-sdk#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (24827): torusresearch/torus-direct-web-sdk#3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:414:13)
E/flutter (24827): torusresearch/torus-direct-web-sdk#4      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:551:18)
E/flutter (24827): torusresearch/torus-direct-web-sdk#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:150:13)
E/flutter (24827): torusresearch/torus-direct-web-sdk#6      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (24827): torusresearch/torus-direct-web-sdk#7      TorusDirect.triggerLogin (package:torus_direct/torus_direct.dart:53:26)
E/flutter (24827): torusresearch/torus-direct-web-sdk#8      _MyAppState._withGoogle (package:torus_direct_example/main.dart:82:24)
E/flutter (24827): torusresearch/torus-direct-web-sdk#9      _MyAppState._login.<anonymous closure> (package:torus_direct_example/main.dart:69:58)
E/flutter (24827): torusresearch/torus-direct-web-sdk#10     _MyAppState._login.<anonymous closure> (package:torus_direct_example/main.dart:67:12)
E/flutter (24827): torusresearch/torus-direct-web-sdk#11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (24827): torusresearch/torus-direct-web-sdk#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (24827): torusresearch/torus-direct-web-sdk#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter (24827): torusresearch/torus-direct-web-sdk#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (24827): torusresearch/torus-direct-web-sdk#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (24827): torusresearch/torus-direct-web-sdk#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (24827): torusresearch/torus-direct-web-sdk#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (24827): torusresearch/torus-direct-web-sdk#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (24827): torusresearch/torus-direct-web-sdk#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (24827): torusresearch/torus-direct-web-sdk#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (24827): torusresearch/torus-direct-web-sdk#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (24827): torusresearch/torus-direct-web-sdk#24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (24827): torusresearch/torus-direct-web-sdk#25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (24827): torusresearch/torus-direct-web-sdk#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#29     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (24827): torusresearch/torus-direct-web-sdk#30     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (24827): torusresearch/torus-direct-web-sdk#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#32     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (24827): torusresearch/torus-direct-web-sdk#33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (24827): torusresearch/torus-direct-web-sdk#34     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (24827): 
```

The only modifications I have done us changing the `clientId` value to match my torus/google application and commenting out a parameter in `TorusDirect.init` which seems to be missing in the library's implementation:

```
        // browserRedirectUri:
        //     Uri.parse('https://scripts.toruswallet.io/redirect.html'),
```

**Comment by michaellee8** [comment]
@nicolaslara Can you indicate which flutter version are you using? It looks like some flutter internal things.

**Comment by nicolaslara** [comment]
Latest version:
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

Also from my pubspec.yaml:

```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

**Comment by michaellee8** [comment]
@nicolaslara It looks like the error comes from here https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/services/message_codecs.dart#L414, but I am unable to reproduce the same error using latest flutter stable on Android. If I commented out `browserRedirectUri` Google Sign-in will complain about `redirect_uri` but not the error you have mentioned. Can you kindly paste the exact code you are using here so that I can try to reproduce it?

**Comment by nicolaslara** [comment]
oh, interesting. I don't have the code with me right now, but I'll post it when I can. I may try to setup everything from scratch to see if it keeps happening.

But the only changes I had made were these:

> changing the clientId value to match my torus/google application and commenting out a parameter in TorusDirect.init which seems to be missing in the library's implementation

I wonder if the error only happens once you have a valid clientid

**Comment by michaellee8** [comment]
@nicolaslara i tried to comment out the parameter as well and it would have passed the message_codecs.dart, the error comes from some Google Sign-in thing, better if I can have the exact code to debug on.

**Comment by nicolaslara** [comment]
@michaellee8 I've added the sample code I've been using here: https://github.com/nicolaslara/libre. It's basically a clone of `torusresearch/torus-direct-flutter-sdk`/example with some variables modified to match what I've setup in google and the torus dashboard. 

The code in the repo is currently using `torusapp://org.torusresearch.torusdirectandroid/redirect` as a redirect uri, but I've experimented with different values. In any case, I think the error is happening before reaching a place where the redirect uri would be a problem

**Comment by PhamNgocPhi** [comment]
I'm facing the same problem, @nicolaslara @michaellee8 are you find any solution for that?

**Comment by michaellee8** [comment]
> I'm facing the same problem, @nicolaslara @michaellee8 are you find any solution for that?

We have recently released 2.0.1 that may solve this problem, can you try that out?

**Comment by PhamNgocPhi** [comment]
@michaellee8 thanks for quick response, I just see v2.0.1 in GitHub but not in pub.dev. So how can I get v2.0.1 in my flutter project 🙃🙃

**Comment by michaellee8** [comment]
@PhamNgocPhi You may try it by specifying a git source in your pubspec https://dart.dev/tools/pub/dependencies#git-packages

**Comment by nicolaslara** [comment]
> I'm facing the same problem, @nicolaslara @michaellee8 are you find any solution for that?

I didn't. I also had issues with the react native version, so ended up moving away from torus altogether. Might revisit this in the future when the apis are more stable.

**Comment by michaellee8** [comment]
> @michaellee8 I don't see this issue when update to v2.0.1, but I face the new problem. I set up follow readme in [https://pub.dev/packages/torus_direct](https://pub.dev/packages/torus_direct) but google always says that invalid request like this image [https://ibb.co/DfyhHTG](https://ibb.co/DfyhHTG). Do you have any idea for that?

Did you configure your app according to the instructions of the iOS and Android Torus Direct SDK? Looks like misconfigured

**Comment by PhamNgocPhi** [comment]
@michaellee8 When i add this line on initTorus method
`browserRedirectUri: Uri.parse('https://scripts.toruswallet.io/redirect.html')` 
it return other problem is **error 400 redirect_uri_mismatch**
I think RedirectUri is not correct, but I try more solution, it still error. Do you have any idea for that :(
